baseurl = "https://szeliga.co/"
languageCode = "en-us"
title = "After Eight Coding"
description = "A developer's blog about Ruby and Go"
theme = "hugo-type-theme"
paginate = 10
PaginatePath = "/"
pygmentsuseclasses = false
pygmentsstyle = "autumn"
pygmentslinenos = "inline"
PygmentsCodeFences= true
disqusShortname = "after-eight-coding"
googleAnalytics = "UA-57222446-2"

[taxonomies]
category = "categories"

[author]
  name = "Szymon Szeliga"

[params]
  author = "Szymon Szeliga"
	name = "After Eight Coding"
  gravatar = "szymon@szeliga.co"
	description = "A developer's blog about Ruby and Go"
	copyright = "by Szymon Szeliga - Powered by [Hugo](//gohugo.io) - Theme: [Type](//github.com/digitalcraftsman/hugo-type-theme)"
  pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasnâ€™t <br> found on the server."
  newer = "Next"
  older = "Previous"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params.social]
	# Insert your accout name and the icon will be shown in the right menu
	rss = true
	homepage = true
	email = "szymon@szeliga.co"
	github = "Szeliga"
	linkedin = "https://www.linkedin.com/in/szymonszeliga"
